### PR TITLE
add occt7.1 include files

### PR DESCRIPTION
**Pull request by mahaidong**
change the following files:

* add  `include` folder from occt7.1
* rewrite build.sh to `gcc -I ./include/opencascade  -shared -fpic ./src/oc_wrap.cxx -std=c++11 -o ./lib/Linux/AMD64/debug/oc.so`
* rewrite how-to-build-in-linux.md,  remove compiling occt parts.

### CODE REVIEW

**Comment by awolven** [comment]
Hi ma.
I already did this.

I moved binaries around and changed directory names, added swig as a
submodule.  The swig submodule needs to be built for Linux AMD64, and the
whole process of generate/build/run needs to be tested for Linux and macos
still.

**Comment by awolven** [comment]
I'm thinking now after I get everything tested, I will want to move all
occt binaries and includes to a separate repo 'occt', make it a submodule
of 'oc' and rebase 'oc' squashing all commits.  By doing so, the binary
component of 'oc' will be minimized into a repo which should almost never
change, keeping clone size to a minimum.  Only the oc.so related binaries
will be kept with oc, keeping oc's clone size in check.

**Comment by mahaidong** [comment]
> I'm thinking now after I get everything tested, I will want to move all occt binaries and includes to a separate repo 'occt', make it a submodule of 'oc' and rebase 'oc' squashing all commits. By doing so, the binary component of 'oc' will be minimized into a repo which should almost never cha...

I use your clang linuxe *.so files . it works for me in ubuntu20. so maybe you can delete the occt *.so folder. 
so far you have two copy of *.so files. one in linux folder, one in occt folder.

**Comment by awolven** [comment]
I removed extra oc.so and oc.dylib in the root folder.  So now
oc.{so,dll,dylib} files are in lib/occt subdirectories, all scripts and
lisp code should point to them there.

**Comment by mahaidong** [comment]
> I removed extra oc.so and oc.dylib in the root folder. So now oc.{so,dll,dylib} files are in lib/occt subdirectories, all scripts and lisp code should point to them there.


I means the occt library.so files.  you have two copys.  one in linux folder, one in occt folder.

**Comment by awolven** [comment]
Thanks for pointing out to me the extraneous shared object directories.

**Pull request closed without merging**
